<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $sublogin = $this->getSublogin(); ?>
<div class="page-title">
    <h1>
    <?php echo $sublogin->getId() ? $this->__('Edit further Login') : $this->__('Create Staff Login'); ?>
    </h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getUrl('sublogin/frontend/edit', array('id' => $sublogin->getData('id'))); ?>" method="post" id="form-validate">
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Further login') ?></h2>
        <?php if ($sublogin->getData('customer_id')): ?>
        <ul class="form-list">
            <li class="field">
                <label for="firstname" class="required"><em>*</em><?php echo $this->__('Customer ID') ?></label>
                <div class="input-box">
                 <?php echo $sublogin->getData('customer_id'); ?>
                </div>
            </li>
        </ul>
        <div class="clearfix">&nbsp;</div>
        <?php endif; ?>

        <ul class="form-list">
            <li class="field">
                <label for="firstname" class="required"><em>*</em><?php echo $this->__('First Name') ?></label>
                <div class="input-box">
                    <input type="text" name="firstname" id="firstname" value="<?php echo $sublogin->getData('firstname'); ?>" title="<?php echo $this->__('Firstname') ?>" class="input-text required-entry" />
                </div>
            </li>
            <li class="field">
                <label for="lastname" class="required"><em>*</em><?php echo $this->__('Last Name') ?></label>
                <div class="input-box">
                    <input type="text" name="lastname" id="lastname" value="<?php echo $sublogin->getData('lastname'); ?>" title="<?php echo $this->__('Lastname') ?>" class="input-text required-entry" />
                </div>
            </li>
        </ul>
        <div class="clearfix">&nbsp;</div>

        <ul class="form-list">
            <li class="field">
                <label for="email" class="required"><em>*</em><?php echo $this->__('E-mail') ?></label>
                <div class="input-box">
                    <input type="text" name="email" id="email" value="<?php echo $sublogin->getData('email'); ?>" title="<?php echo $this->__('Email') ?>" class="input-text required-entry" />
                </div>
            </li>
        </ul>
        <div class="clearfix">&nbsp;</div>

        <ul class="form-list">
            <li class="field">
                <label for="password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                <div class="input-box">
                    <input type="text" name="password" id="password" value="" title="<?php echo $this->__('Password') ?>"
                        class="input-text<?php if (!$sublogin->getId()) echo ' required-entry';?>" />
                </div>
            </li>
        </ul>
        <div class="clearfix">&nbsp;</div>

        <ul class="form-list">
            <li class="field">
                <label for="active" class="required"><em>*</em><?php echo $this->__('Active') ?></label>
                <div class="dropdown-box">
                     <select name="active" class="active">
                         <option name="yes" value="1" <?php if ($sublogin->getActive())echo 'selected="selected"';?>><?php echo $this->__('Yes'); ?></option>
                         <option name="no" value="0" <?php if (!$sublogin->getActive())echo 'selected="selected"';?>><?php echo $this->__('No'); ?></option>
                     </select>
                </div>
            </li>
        </ul>
        <div class="clearfix">&nbsp;</div>
    </div>


    <div class="buttons-set">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <p class="back-link"><a href="<?php echo $this->getUrl('sublogin/frontend') ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button type="submit" title="<?php echo $this->__('Save') ?>" class="button"><span><span><?php echo $this->__('Save') ?></span></span></button>
    </div>
</form>
