<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="page-title">
    <h1><?php echo $this->__('My Staff Logins') ?></h1>
</div>

<?php if (!Mage::helper('sublogin')->getCurrentSublogin()): ?>
<p><?php echo $this->__('Manage and edit your staff logins. Possibility for editing and creating additional logins for employees and colleagues.'); ?></p>
<?php endif;?>

<?php echo $this->getToolbarHtml() ?>
    <table class="data-table" id="my-sublogins">
     <tbody>
            <tr class="headings">
                    <th><span class="nobr"><?php echo $this->__('Customer ID') ?></span></th>
                    <th><span class="nobr"><?php echo $this->__('First Name') ?></span></th>
                    <th><span class="nobr"><?php echo $this->__('Last Name') ?></span></th>
                    <th><span class="nobr"><?php echo $this->__('E-Mail') ?></span></th>
                    <th><span class="nobr"><?php echo $this->__('Active') ?></span></th>
                    <th><span class="nobr"><?php echo $this->__('Expire Date') ?></span></th>
                    <?php if (!Mage::helper('sublogin')->getCurrentSublogin()): ?>
                        <th><span class="nobr"><?php echo $this->__('Actions'); ?></span></th>
                    <?php endif;?>
            </tr>
            <?php foreach ($this->getCollection() as $i=>$_sublogin): ?>
            <tr class="<?php echo $i%2?'even':'odd'?>">

                    <td><span class="nobr"><?php echo $_sublogin->getData('customer_id') ?></span></td>
                    <td><span class="nobr"><?php echo $_sublogin->getData('firstname') ?></span></td>
                    <td><span class="nobr"><?php echo $_sublogin->getData('lastname') ?></span></td>
                    <td><span class="nobr"><?php echo $_sublogin->getData('email') ?></span></td>
                    <td><span class="nobr"><?php echo $_sublogin->getData('active') ? $this->__('Yes') : $this->__('No'); ?></span></td>
                    <td><span class="nobr"><?php echo ($_sublogin->getData('active'))?$this->dateFormat($_sublogin->getData('expire_date')):'-'; ?></span></td>
                    <?php if (!Mage::helper('sublogin')->getCurrentSublogin()): ?>
                        <td><span class="nobr"></span>
                        <a href="<?php echo $this->getUrl('sublogin/frontend/edit/', array('id' => $_sublogin->getData('id'))); ?>"><img src="<?php echo $this->getSkinUrl('images/sublogin/edit.png'); ?>" alt="edit" /></a>&nbsp;&nbsp;&nbsp;&nbsp;
                        <a href="<?php echo $this->getUrl('sublogin/frontend/delete/', array('id' => $_sublogin->getData('id'))); ?>"><img src="<?php echo $this->getSkinUrl('images/sublogin/delete.png'); ?>" alt="delete" /></a>
                        </td>
                    <?php endif;?>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php echo $this->getToolbarHtml() ?>
<div class="buttons-set">
    <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
    <?php if (!Mage::helper('sublogin')->getCurrentSublogin()): ?>
        <button type="button" onclick="window.location='<?php echo $this->getUrl('sublogin/frontend/create/') ?>';" title="<?php echo $this->__('Create staff login') ?>" class="button"><span><span><?php echo $this->__('Create staff login') ?></span></span></button>
    <?php endif; ?>
</div>
