<div class="promo-blocks">

        <div class="grid-container">
            <a href="/new.html" class="grid12-12 new-products-header">
                <h3>Checkout the latest additions to our product range</h3>
            </a>
            <div class="grid12-3 hide-below-768"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('block_new_products_01')->toHtml(); ?></div>
            <div class="grid12-3 hide-below-768"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('block_new_products_02')->toHtml(); ?></div>
            <div class="grid12-3 hide-below-768"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('block_new_products_03')->toHtml(); ?></div>
            <div class="grid12-3 hide-below-768"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('block_new_products_04')->toHtml(); ?></div>
        </div>

    </div>




