<?php
/**
 * Appmerce - Applications for Ecommerce
 * http://ww.appmerce.com
 *
 * @extension   eWAY Rapid API 3.1
 * @type        Payment method
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category    Magento
 * @package     Appmerce_Eway
 * @copyright   Copyright (c) 2011-2014 Appmerce (http://www.appmerce.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<h2><?php echo Mage::helper('eway')->__('You will be redirected to the payment gateway in a few seconds.'); ?></h2>
<form name="eway" id="eway_review_form" action="<?php echo $this->getFormAction(); ?>" method="post" accept-charset="UTF-8">
    <fieldset>
      <?php foreach ($this->getFormData() as $name => $value) { ?>
          <input type="hidden" name="<?php echo($name); ?>" value="<?php echo($value); ?>" />
      <?php } ?>
    </fieldset>
</form>

<script type="text/javascript">
    //<![CDATA[
    var review = new VarienForm('eway_review_form', '');
    Event.observe(window, 'load', function() {
        review.submit();
    });
    //]]>
</script>